-- Generated by scripts/migrate-mssql-to-postgres.ps1
BEGIN;

TRUNCATE TABLE public."roles", public."users", public."rooms", public."asset_categories", public."assets", public."maintenance_requests", public."asset_usages", public."notifications", public."chat_messages", public."audit_logs", public."technician_coverage_rules", public."ticket_attachments" RESTART IDENTITY CASCADE;

INSERT INTO public."roles" ("id", "description", "name")
VALUES
    (1, 'Quản trị viên hệ thống', 'ADMIN'),
    (2, 'Nhân viên', 'STAFF'),
    (10002, 'Nhan vien bao tri', 'MAINTENANCE');

INSERT INTO public."users" ("id", "created_at", "email", "email_verification_expiry", "email_verification_token", "email_verified", "full_name", "is_active", "password", "password_reset_expiry", "password_reset_token", "phone", "updated_at", "username", "role_id")
VALUES
    (1, '2026-03-28 07:54:51.0733333', 'admin@fptpoly.edu.vn', NULL, NULL, NULL, 'Quản trị viên', TRUE, '$2a$12$LqlPKVNgTHuCrXk2FczoF.j7axQC2JgzjH45CTzMijBUIryzZeif6', NULL, NULL, '0236123456', '2026-03-28 07:54:51.0733333', 'admin', 1),
    (2, '2026-03-28 07:54:51.1266667', 'nhanvien@fptpoly.edu.vn', NULL, NULL, NULL, 'Nguyễn Văn A', TRUE, '$2a$12$LqlPKVNgTHuCrXk2FczoF.j7axQC2JgzjH45CTzMijBUIryzZeif6', NULL, NULL, '0236654321', '2026-03-31 15:09:17.1037700', 'nhanvien', 2),
    (10005, '2026-03-31 16:16:56.9721280', 'lephanphuquoc@gmail.com', NULL, NULL, TRUE, 'Phú Quốc Lê Phan', TRUE, '$2a$12$HJPXAUNEGEsxPqbmM8GVG.RJhD6vK6e4m0Kvi2XEYD5JQ5UdDyTN.', '2026-03-31 16:52:44.4947820', '2340076f-bf6b-4f7a-ad0e-094903138a62', NULL, '2026-03-31 17:44:49.3208890', 'admin1', 10002);

INSERT INTO public."rooms" ("id", "building", "capacity", "code", "created_at", "description", "floor", "is_active", "name")
VALUES
    (1, 'Tòa A', 40, 'P101', '2026-03-28 07:54:51.2333333', NULL, 1, TRUE, 'Phòng học 101'),
    (2, 'Tòa A', 40, 'P102', '2026-03-28 07:54:51.2333333', NULL, 1, TRUE, 'Phòng học 102'),
    (3, 'Tòa A', 30, 'P201', '2026-03-28 07:54:51.2333333', NULL, 2, TRUE, 'Phòng thực hành 201'),
    (4, 'Tòa A', 30, 'P202', '2026-03-28 07:54:51.2333333', NULL, 2, TRUE, 'Phòng Lab 202'),
    (5, 'Tòa B', 60, 'P301', '2026-03-28 07:54:51.2333333', NULL, 3, TRUE, 'Phòng hội thảo'),
    (6, 'Tòa B', 20, 'P401', '2026-03-28 07:54:51.2333333', NULL, 4, TRUE, 'Phòng giáo viên'),
    (7, 'Tòa B', 15, 'P501', '2026-03-28 07:54:51.2333333', NULL, 5, TRUE, 'Phòng họp'),
    (8, 'Tòa C', 100, 'TT', '2026-03-28 07:54:51.2333333', NULL, 1, TRUE, 'Thư viện'),
    (10002, NULL, NULL, 'STORE', '2026-03-31 17:12:02.2088770', 'Kho mac dinh cho thiet bi moi tao va thiet bi da tra.', NULL, TRUE, 'Store Room');

INSERT INTO public."asset_categories" ("id", "created_at", "description", "icon", "name")
VALUES
    (1, '2026-03-28 07:54:51.2700000', 'Máy tính bàn và laptop', 'bi-pc-display', 'Máy tính'),
    (2, '2026-03-28 07:54:51.2700000', 'Projector và màn chiếu', 'bi-projector', 'Máy chiếu'),
    (3, '2026-03-28 07:54:51.2700000', 'Máy lạnh và điều hòa không khí', 'bi-thermometer', 'Điều hòa'),
    (4, '2026-03-28 07:54:51.2700000', 'Bàn học, ghế ngồi', 'bi-easel', 'Bàn ghế'),
    (5, '2026-03-28 07:54:51.2700000', 'Router, Switch, Access Point', 'bi-router', 'Thiết bị mạng'),
    (6, '2026-03-28 07:54:51.2700000', 'Monitor và TV', 'bi-display', 'Màn hình'),
    (7, '2026-03-28 07:54:51.2700000', 'Printer và Scanner', 'bi-printer', 'Máy in'),
    (8, '2026-03-28 07:54:51.2700000', 'Loa, microphone', 'bi-speaker', 'Thiết bị âm thanh');

INSERT INTO public."assets" ("id", "brand", "created_at", "description", "is_active", "model", "name", "purchase_date", "purchase_price", "qa_code", "qr_code_path", "serial_number", "status", "updated_at", "warranty_expiry", "category_id", "created_by", "room_id")
VALUES
    (1, 'Dell', '2026-03-28 07:54:51.3600000', '', TRUE, 'Optiplex 7090', 'Máy tính DELL Optiplex 001', '2023-01-15', NULL, 'FPT-PC-001', NULL, 'SN-DELL-001', 'AVAILABLE', '2026-04-02 14:09:27.9055030', NULL, 1, NULL, 10002),
    (2, 'Dell', '2026-03-28 07:54:51.3600000', '', TRUE, 'Optiplex 7090', 'Máy tính DELL Optiplex 002', '2023-01-15', NULL, 'FPT-PC-002', NULL, 'SN-DELL-002', 'BROKEN', '2026-04-01 22:45:33.5511340', NULL, 1, NULL, 10002),
    (3, 'Epson', '2026-03-28 07:54:51.3600000', '', TRUE, 'EB-X49', 'Máy chiếu Epson EB-X49', '2022-06-01', NULL, 'FPT-PROJ-001', NULL, 'SN-EPS-001', 'AVAILABLE', '2026-04-01 20:37:37.0030270', NULL, 2, NULL, 10002),
    (4, 'Daikin', '2026-03-28 07:54:51.3600000', NULL, TRUE, 'FTKF35XVMV', 'Điều hòa Daikin 1.5HP phòng 101', '2023-03-10', NULL, 'FPT-AC-001', NULL, 'SN-DAI-001', 'AVAILABLE', '2026-04-01 20:37:55.0116360', NULL, 3, NULL, 10002),
    (5, 'Dell', '2026-03-28 07:54:51.3600000', '', TRUE, 'Inspiron 15', 'Laptop Dell Inspiron 15', '2021-08-20', NULL, 'FPT-PC-003', NULL, 'SN-DELL-003', 'AVAILABLE', '2026-04-01 20:38:36.6859410', NULL, 1, NULL, 10002),
    (6, 'ViewSonic', '2026-03-28 07:54:51.3600000', '', TRUE, 'PA503S', 'Máy chiếu ViewSonic PA503S', '2022-09-15', NULL, 'FPT-PROJ-002', NULL, 'SN-VS-001', 'AVAILABLE', '2026-04-01 20:39:09.0721580', NULL, 2, NULL, 10002);

INSERT INTO public."maintenance_requests" ("id", "actual_cost", "assignment_source", "description", "estimated_cost", "issue_type", "last_activity_at", "priority", "reported_at", "reported_room_snapshot", "resolution_note", "resolved_at", "sla_breached_at", "sla_due_at", "status", "ticket_code", "asset_id", "assigned_to", "reported_by")
VALUES
    (1, NULL, NULL, 'bảo trì', NULL, 'MAINTENANCE', NULL, 'HIGH', '2026-03-15 15:05:10.1002946', NULL, 'a', '2026-03-31 15:21:29.6908108', NULL, NULL, 'RESOLVED', NULL, 1, 1, 1),
    (2, NULL, NULL, 'OK', NULL, 'MAINTENANCE', '2026-04-01 17:41:22.8563540', 'NORMAL', '2026-03-31 17:24:08.4261861', NULL, 'Ok', '2026-03-31 17:45:35.7869417', NULL, NULL, 'RESOLVED', NULL, 1, 1, 1),
    (3, NULL, 'MANUAL', '123', NULL, 'BROKEN', '2026-04-01 19:36:03.5933270', 'NORMAL', '2026-04-01 19:01:44.0259916', 'Store Room', 'Resolved from React workspace', '2026-04-01 19:36:03.5644607', NULL, '2026-04-02 03:01:44.0259920', 'RESOLVED', 'TKT-1775044904026', 1, 1, 1),
    (4, NULL, 'AUTO', 'FPT-PC-002', NULL, 'BROKEN', '2026-04-01 19:35:44.3267250', 'NORMAL', '2026-04-01 19:25:36.4209376', 'Store Room', 'Resolved from React workspace', '2026-04-01 19:35:44.2964704', NULL, '2026-04-02 03:25:36.4209380', 'RESOLVED', 'TKT-1775046336420', 1, 1, 1),
    (5, NULL, 'MANUAL', '12', NULL, 'BROKEN', '2026-04-01 20:36:01.6525520', 'NORMAL', '2026-04-01 19:36:19.5444987', 'Phòng th?c hành 201', NULL, NULL, NULL, '2026-04-02 03:36:19.5444990', 'CANCELLED', 'TKT-1775046979544', 2, 10005, 1),
    (6, NULL, 'AUTO', '12', NULL, 'BROKEN', '2026-04-02 14:05:21.8661980', 'NORMAL', '2026-04-01 22:45:33.5069468', 'Store Room', NULL, NULL, '2026-04-02 14:04:56.0864440', '2026-04-02 06:45:33.5069470', 'CANCELLED', 'TKT-1775058333506', 2, 10005, 1);

INSERT INTO public."asset_usages" ("id", "check_in_time", "check_out_time", "created_at", "note", "purpose", "status", "asset_id", "room_from_id", "room_to_id", "user_id")
VALUES
    (1, '2026-03-31 15:16:09.7609310', '2026-03-31 15:16:17.8759221', '2026-03-31 15:16:09.7748830', 'Hoàn trả thiết bị', '', 'COMPLETED', 3, 1, 5, 1),
    (2, '2026-03-31 15:21:07.7010299', '2026-03-31 15:21:34.4380497', '2026-03-31 15:21:07.7043210', 'Hoàn trả thiết bị', '', 'COMPLETED', 3, 5, 5, 1),
    (3, '2026-03-31 15:24:29.7780867', '2026-03-31 15:24:36.9675180', '2026-03-31 15:24:29.7797170', 'Hoàn trả thiết bị', '', 'COMPLETED', 1, 3, 4, 1),
    (4, '2026-03-31 15:25:42.0269960', '2026-03-31 15:53:12.5569817', '2026-03-31 15:25:42.0269960', 'Hoàn trả thiết bị', '', 'COMPLETED', 3, NULL, NULL, 1),
    (5, '2026-03-31 15:54:34.7655160', '2026-03-31 16:15:10.8775599', '2026-03-31 15:54:34.7666370', 'Hoàn trả thiết bị', '', 'COMPLETED', 1, NULL, 1, 1),
    (6, '2026-03-31 17:22:50.8108594', '2026-03-31 17:22:58.3140445', '2026-03-31 17:22:50.8303930', 'Hoàn trả thiết bị', 'Test', 'COMPLETED', 1, 2, 1, 1),
    (7, '2026-03-31 17:52:31.2227779', '2026-03-31 17:52:34.9118106', '2026-03-31 17:52:31.2263130', 'Hoàn trả thiết bị', '', 'COMPLETED', 1, 10002, 2, 1),
    (8, '2026-03-31 17:57:48.6588759', '2026-03-31 21:33:05.9035552', '2026-03-31 17:57:48.6623030', 'Phiếu sử dụng được đóng do thiết bị được đánh dấu thất lạc.', '', 'CANCELLED', 1, 10002, NULL, 1),
    (9, '2026-04-01 20:37:15.9989353', '2026-04-01 20:37:18.8046055', '2026-04-01 20:37:16.0026140', 'Checked out from React console', '', 'COMPLETED', 2, 3, 1, 1),
    (10, '2026-04-01 20:37:35.3357572', '2026-04-01 20:37:36.9987951', '2026-04-01 20:37:35.3363090', 'Checked out from React console', '', 'COMPLETED', 3, NULL, 7, 1),
    (11, '2026-04-01 20:37:52.9566783', '2026-04-01 20:37:54.9990300', '2026-04-01 20:37:52.9571820', 'Checked out from React console', '', 'COMPLETED', 4, 1, NULL, 1),
    (12, '2026-04-01 20:38:34.0313429', '2026-04-01 20:38:36.6716723', '2026-04-01 20:38:34.0317540', 'Checked out from React console', '', 'COMPLETED', 5, 5, NULL, 1),
    (13, '2026-04-01 20:38:54.5005497', '2026-04-01 20:39:09.0688942', '2026-04-01 20:38:54.5014550', 'Checked out from React console', '', 'COMPLETED', 6, 4, NULL, 1),
    (14, '2026-04-01 22:37:42.8797116', '2026-04-01 22:37:57.4291314', '2026-04-01 22:37:42.8876720', 'Checked out from React console', '', 'COMPLETED', 1, 10002, NULL, 1),
    (15, '2026-04-01 22:38:58.0775047', '2026-04-01 22:39:16.4383474', '2026-04-01 22:38:58.0916700', 'Checked out from React console', '', 'COMPLETED', 1, 10002, NULL, 1),
    (16, '2026-04-01 22:42:28.9572476', '2026-04-02 14:05:36.2527053', '2026-04-01 22:42:28.9583270', 'Checked out from React console', '', 'COMPLETED', 1, 10002, NULL, 1),
    (10009, '2026-04-02 14:09:20.5901581', '2026-04-02 14:09:27.8986243', '2026-04-02 14:09:20.5923960', 'Checked out from React console', '', 'COMPLETED', 1, 10002, NULL, 1);

INSERT INTO public."notifications" ("id", "count", "created_at", "href", "icon", "is_archived", "is_read", "message", "notification_key", "title", "tone", "updated_at", "user_id")
VALUES
    (1, 1, '2026-03-31 15:33:16.5575670', '/assets?status=MAINTENANCE', 'bi-wrench-adjustable-circle', TRUE, FALSE, '1 thi?t b? hi?n ? tr?ng thái b?o trì.', 'assets-maintenance', 'Thi?t b? dang b?o trì', 'info', '2026-03-31 15:43:02.6585010', 1),
    (2, 1, '2026-03-31 15:33:16.5625170', '/usages?status=ACTIVE', 'bi-arrow-left-right', TRUE, FALSE, '1 lu?t mu?n dang ho?t d?ng.', 'usages-active', 'Thi?t b? dang du?c mu?n', 'primary', '2026-03-31 15:43:02.6596920', 1),
    (3, 1, '2026-03-31 15:43:02.6439660', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001) t?i không d?i phòng.', 'usage-checkin-4', 'Check-in m?i', 'primary', '2026-03-31 15:53:04.6334680', 1),
    (4, 1, '2026-03-31 15:43:02.6466010', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-3', 'Check-out m?i', 'success', '2026-03-31 15:53:04.6378600', 1),
    (5, 1, '2026-03-31 15:43:02.6485130', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001) t?i Phòng Lab 202.', 'usage-checkin-3', 'Check-in m?i', 'primary', '2026-03-31 15:53:04.6412050', 1),
    (6, 1, '2026-03-31 15:43:02.6505380', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001).', 'usage-checkout-2', 'Check-out m?i', 'success', '2026-03-31 15:53:04.6438890', 1),
    (7, 1, '2026-03-31 15:43:02.6516340', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001) t?i Phòng h?i th?o.', 'usage-checkin-2', 'Check-in m?i', 'primary', '2026-03-31 15:53:04.6480940', 1),
    (8, 1, '2026-03-31 15:43:02.6532420', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001).', 'usage-checkout-1', 'Check-out m?i', 'success', '2026-03-31 15:53:04.6529060', 1),
    (9, 1, '2026-03-31 15:43:02.6542780', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001) t?i Phòng h?i th?o.', 'usage-checkin-1', 'Check-in m?i', 'primary', '2026-03-31 15:53:04.6565660', 1),
    (10, 1, '2026-03-31 15:43:02.6558390', '/maintenance', 'bi-tools', TRUE, TRUE, 'Qu?n tr? viên v?a t?o yêu c?u b?o trì d?nh k? cho thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'maintenance-created-1', 'Yêu c?u b?o trì m?i', 'warning', '2026-03-31 15:53:04.6598340', 1),
    (11, 1, '2026-03-31 15:53:12.6252920', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy chi?u Epson EB-X49 (FPT-PROJ-001).', 'usage-checkout-4', 'Check-out m?i', 'success', '2026-03-31 15:53:15.5581330', 1),
    (12, 1, '2026-03-31 15:54:34.8123530', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001) t?i Phòng h?c 101.', 'usage-checkin-5', 'Check-in m?i', 'primary', '2026-03-31 15:55:06.1809130', 1),
    (13, 1, '2026-03-31 16:15:10.9678930', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-5', 'Check-out m?i', 'success', '2026-03-31 17:07:23.5283230', 1),
    (14, 1, '2026-03-31 17:22:51.0146690', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001) t?i Phòng h?c 101.', 'usage-checkin-6', 'Check-in m?i', 'primary', '2026-03-31 17:24:35.5023360', 1),
    (15, 1, '2026-03-31 17:22:58.4707950', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-6', 'Check-out m?i', 'success', '2026-03-31 17:24:35.5095680', 1),
    (16, 1, '2026-03-31 17:24:08.5476590', '/maintenance', 'bi-tools', TRUE, TRUE, 'Qu?n tr? viên v?a t?o yêu c?u b?o trì d?nh k? cho thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'maintenance-created-2', 'Yêu c?u b?o trì m?i', 'warning', '2026-03-31 17:24:35.5187370', 1),
    (17, 1, '2026-03-31 17:52:31.4327340', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001) t?i Phòng h?c 102.', 'usage-checkin-7', 'Check-in m?i', 'primary', '2026-03-31 21:30:49.7982150', 1),
    (18, 1, '2026-03-31 17:52:35.0568800', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-7', 'Check-out m?i', 'success', '2026-03-31 21:30:49.8019510', 1),
    (19, 1, '2026-03-31 17:57:48.7950230', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Qu?n tr? viên v?a check-in thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001) t?i không d?i phòng.', 'usage-checkin-8', 'Check-in m?i', 'primary', '2026-03-31 21:30:49.8040560', 1),
    (20, 1, '2026-03-31 21:33:05.9817290', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Qu?n tr? viên v?a check-out thi?t b? Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-8', 'Check-out m?i', 'success', '2026-04-01 17:29:20.9318710', 1),
    (21, 1, '2026-04-01 17:29:07.6602250', '/tickets/2', 'bi-chat-dots', TRUE, TRUE, 'Qu?n tr? viên: 12', 'chat-ticket-2-1', 'Tin nh?n m?i trong null', 'primary', '2026-04-01 17:40:05.0694050', 1),
    (26, 1, '2026-04-01 19:01:44.0668590', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Qu?n tr? viên dã t?o ticket TKT-1775044904026 cho Máy tính DELL Optiplex 001.', 'ticket_created-ticket-3-1', 'Ticket TKT-1775044904026', 'info', '2026-04-01 19:01:49.3720850', 1),
    (27, 1, '2026-04-01 19:01:44.0722020', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Qu?n tr? viên dã t?o ticket TKT-1775044904026 cho Máy tính DELL Optiplex 001.', 'ticket_created-ticket-3-10005', 'Ticket TKT-1775044904026', 'info', '2026-04-01 19:14:19.4889740', 10005),
    (28, 1, '2026-04-01 19:01:44.1570330', '/tickets', 'bi-tools', TRUE, TRUE, 'Quản trị viên vừa tạo yêu cầu báo hỏng cho thiết bị Máy tính DELL Optiplex 001 (FPT-PC-001).', 'maintenance-created-3', 'Yêu cầu bảo trì mới', 'warning', '2026-04-01 19:39:50.1591890', 1),
    (30, 1, '2026-04-01 19:08:08.9915330', '/tickets/3', 'bi-chat-dots', TRUE, TRUE, 'Phú Quốc Lê Phan: 12', 'chat-ticket-3-1', 'Tin nhắn mới trong TKT-1775044904026', 'primary', '2026-04-01 19:39:50.1638940', 1),
    (31, 7, '2026-04-01 19:08:08.9974970', '/tickets/3', 'bi-chat-dots', TRUE, TRUE, 'Phú Quốc Lê Phan: 111', 'chat-ticket-3-10005', 'Tin nhắn mới trong TKT-1775044904026', 'primary', '2026-04-01 19:14:18.7806470', 10005),
    (39, 3, '2026-04-01 19:17:47.8924670', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775044904026 đã được giao cho Phú Quốc Lê Phan.', 'ticket_assigned-ticket-3-1', 'Ticket TKT-1775044904026', 'warning', '2026-04-01 19:39:50.1682420', 1),
    (40, 2, '2026-04-01 19:17:47.8961460', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775044904026 đã được giao cho Phú Quốc Lê Phan.', 'ticket_assigned-ticket-3-10005', 'Ticket TKT-1775044904026', 'warning', '2026-04-01 19:24:30.2891110', 10005),
    (41, 1, '2026-04-01 19:25:36.4442870', '/tickets/4', 'bi-tools', TRUE, TRUE, 'Quản trị viên đã tạo ticket TKT-1775046336420 cho Máy tính DELL Optiplex 001.', 'ticket_created-ticket-4-1', 'Ticket TKT-1775046336420', 'info', '2026-04-01 19:39:50.1715410', 1),
    (42, 1, '2026-04-01 19:25:36.4485380', '/tickets/4', 'bi-tools', FALSE, FALSE, 'Quản trị viên đã tạo ticket TKT-1775046336420 cho Máy tính DELL Optiplex 001.', 'ticket_created-ticket-4-10005', 'Ticket TKT-1775046336420', 'info', '2026-04-01 19:25:36.4485380', 10005),
    (44, 1, '2026-04-01 19:25:36.5138020', '/tickets', 'bi-tools', TRUE, TRUE, 'Quản trị viên vừa tạo yêu cầu báo hỏng cho thiết bị Máy tính DELL Optiplex 001 (FPT-PC-001).', 'maintenance-created-4', 'Yêu cầu bảo trì mới', 'warning', '2026-04-01 19:39:50.1735970', 1),
    (45, 1, '2026-04-01 19:35:40.8971370', '/tickets/4', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775046336420 đã chuyển sang Đang xử lý.', 'ticket_status_changed-ticket-4-1', 'Ticket TKT-1775046336420', 'info', '2026-04-01 19:39:50.1772300', 1),
    (46, 1, '2026-04-01 19:35:40.9040100', '/tickets/4', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775046336420 đã chuyển sang Đang xử lý.', 'ticket_status_changed-ticket-4-10005', 'Ticket TKT-1775046336420', 'info', '2026-04-01 19:35:40.9040100', 10005),
    (47, 1, '2026-04-01 19:35:44.3022420', '/tickets/4', 'bi-tools', TRUE, TRUE, 'Quản trị viên đã giải quyết ticket TKT-1775046336420.', 'ticket_resolved-ticket-4-1', 'Ticket TKT-1775046336420', 'success', '2026-04-01 19:39:50.1804300', 1),
    (48, 1, '2026-04-01 19:35:50.9522930', '/tickets/3', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775044904026 đã được giao cho Phú Quốc Lê Phan.', 'ticket_assigned-ticket-3-10005', 'Ticket TKT-1775044904026', 'warning', '2026-04-01 19:35:50.9522930', 10005),
    (49, 1, '2026-04-01 19:36:02.6332540', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775044904026 đã chuyển sang Đã giải quyết.', 'ticket_status_changed-ticket-3-1', 'Ticket TKT-1775044904026', 'info', '2026-04-01 19:39:50.1837910', 1),
    (50, 1, '2026-04-01 19:36:02.6368840', '/tickets/3', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775044904026 đã chuyển sang Đã giải quyết.', 'ticket_status_changed-ticket-3-10005', 'Ticket TKT-1775044904026', 'info', '2026-04-01 19:36:02.6368840', 10005),
    (51, 1, '2026-04-01 19:36:03.5699000', '/tickets/3', 'bi-tools', TRUE, TRUE, 'Quản trị viên đã giải quyết ticket TKT-1775044904026.', 'ticket_resolved-ticket-3-1', 'Ticket TKT-1775044904026', 'success', '2026-04-01 19:39:50.1869090', 1),
    (52, 1, '2026-04-01 19:36:19.5616790', '/tickets/5', 'bi-tools', TRUE, TRUE, 'Quản trị viên đã tạo ticket TKT-1775046979544 cho Máy tính DELL Optiplex 002.', 'ticket_created-ticket-5-1', 'Ticket TKT-1775046979544', 'info', '2026-04-01 19:39:50.1895060', 1),
    (53, 1, '2026-04-01 19:36:19.5666800', '/tickets/5', 'bi-tools', FALSE, FALSE, 'Quản trị viên đã tạo ticket TKT-1775046979544 cho Máy tính DELL Optiplex 002.', 'ticket_created-ticket-5-10005', 'Ticket TKT-1775046979544', 'info', '2026-04-01 19:36:19.5666800', 10005),
    (54, 1, '2026-04-01 19:36:29.1865820', '/tickets', 'bi-tools', TRUE, TRUE, 'Quản trị viên vừa tạo yêu cầu báo hỏng cho thiết bị Máy tính DELL Optiplex 002 (FPT-PC-002).', 'maintenance-created-5', 'Yêu cầu bảo trì mới', 'warning', '2026-04-01 19:39:50.1927100', 1),
    (55, 1, '2026-04-01 19:36:30.2654960', '/tickets/5', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775046979544 đã được giao cho Phú Quốc Lê Phan.', 'ticket_assigned-ticket-5-1', 'Ticket TKT-1775046979544', 'warning', '2026-04-01 19:39:50.1952960', 1),
    (56, 1, '2026-04-01 19:36:30.2706230', '/tickets/5', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775046979544 đã được giao cho Phú Quốc Lê Phan.', 'ticket_assigned-ticket-5-10005', 'Ticket TKT-1775046979544', 'warning', '2026-04-01 19:36:30.2706230', 10005),
    (57, 1, '2026-04-01 20:36:01.5562820', '/tickets/5', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775046979544 đã chuyển sang Đã hủy.', 'ticket_status_changed-ticket-5-1', 'Ticket TKT-1775046979544', 'info', '2026-04-01 20:38:28.5777670', 1),
    (58, 1, '2026-04-01 20:36:01.5806450', '/tickets/5', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775046979544 đã chuyển sang Đã hủy.', 'ticket_status_changed-ticket-5-10005', 'Ticket TKT-1775046979544', 'info', '2026-04-01 20:36:01.5812730', 10005),
    (59, 1, '2026-04-01 20:37:22.9074510', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Máy tính DELL Optiplex 002 (FPT-PC-002).', 'usage-checkout-9', 'Check-out mới', 'success', '2026-04-01 20:38:28.5890150', 1),
    (61, 1, '2026-04-01 20:37:24.0951380', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Máy tính DELL Optiplex 002 (FPT-PC-002) tới Phòng học 101.', 'usage-checkin-9', 'Check-in mới', 'primary', '2026-04-01 20:38:28.5966880', 1),
    (62, 1, '2026-04-01 20:37:37.6817530', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Máy chiếu Epson EB-X49 (FPT-PROJ-001).', 'usage-checkout-10', 'Check-out mới', 'success', '2026-04-01 20:38:28.6055070', 1),
    (64, 1, '2026-04-01 20:37:41.6105920', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Máy chiếu Epson EB-X49 (FPT-PROJ-001) tới Phòng họp.', 'usage-checkin-10', 'Check-in mới', 'primary', '2026-04-01 20:38:28.6130950', 1),
    (65, 1, '2026-04-01 20:37:56.3176380', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Điều hòa Daikin 1.5HP phòng 101 (FPT-AC-001).', 'usage-checkout-11', 'Check-out mới', 'success', '2026-04-01 20:38:28.6242220', 1),
    (67, 1, '2026-04-01 20:37:59.1274700', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Điều hòa Daikin 1.5HP phòng 101 (FPT-AC-001) tới không đổi phòng.', 'usage-checkin-11', 'Check-in mới', 'primary', '2026-04-01 20:38:28.6320110', 1),
    (68, 1, '2026-04-01 20:38:39.2127970', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Laptop Dell Inspiron 15 (FPT-PC-003).', 'usage-checkout-12', 'Check-out mới', 'success', '2026-04-01 22:42:27.2811950', 1),
    (70, 1, '2026-04-01 20:38:39.2213360', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Laptop Dell Inspiron 15 (FPT-PC-003) tới không đổi phòng.', 'usage-checkin-12', 'Check-in mới', 'primary', '2026-04-01 22:42:27.2866070', 1),
    (71, 1, '2026-04-01 20:39:01.5684570', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Máy chiếu ViewSonic PA503S (FPT-PROJ-002) tới không đổi phòng.', 'usage-checkin-13', 'Check-in mới', 'primary', '2026-04-01 22:42:27.2913670', 1),
    (73, 1, '2026-04-01 20:39:10.0232780', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Máy chiếu ViewSonic PA503S (FPT-PROJ-002).', 'usage-checkout-13', 'Check-out mới', 'success', '2026-04-01 22:42:27.2935700', 1),
    (75, 1, '2026-04-01 22:45:33.5371370', '/tickets/6', 'bi-tools', TRUE, TRUE, 'Quản trị viên đã tạo ticket TKT-1775058333506 cho Máy tính DELL Optiplex 002.', 'ticket_created-ticket-6-1', 'Ticket TKT-1775058333506', 'info', '2026-04-02 14:09:43.4570750', 1),
    (76, 1, '2026-04-01 22:45:33.5478900', '/tickets/6', 'bi-tools', FALSE, FALSE, 'Quản trị viên đã tạo ticket TKT-1775058333506 cho Máy tính DELL Optiplex 002.', 'ticket_created-ticket-6-10005', 'Ticket TKT-1775058333506', 'info', '2026-04-01 22:45:33.5478900', 10005),
    (10034, 1, '2026-04-02 14:04:56.2408200', '/tickets/6', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775058333506 đã quá hạn SLA.', 'ticket_overdue-ticket-6-10005', 'Ticket TKT-1775058333506', 'danger', '2026-04-02 14:04:56.2408200', 10005),
    (10035, 1, '2026-04-02 14:04:56.2742120', '/tickets/6', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775058333506 đã quá hạn SLA.', 'ticket_overdue-ticket-6-1', 'Ticket TKT-1775058333506', 'danger', '2026-04-02 14:09:43.4687100', 1),
    (10036, 1, '2026-04-02 14:05:21.8177920', '/tickets/6', 'bi-tools', FALSE, FALSE, 'Ticket TKT-1775058333506 đã chuyển sang Đã hủy.', 'ticket_status_changed-ticket-6-10005', 'Ticket TKT-1775058333506', 'info', '2026-04-02 14:05:21.8177920', 10005),
    (10037, 1, '2026-04-02 14:05:21.8316290', '/tickets/6', 'bi-tools', TRUE, TRUE, 'Ticket TKT-1775058333506 đã chuyển sang Đã hủy.', 'ticket_status_changed-ticket-6-1', 'Ticket TKT-1775058333506', 'info', '2026-04-02 14:09:43.4761380', 1),
    (10038, 1, '2026-04-02 14:09:20.6696570', '/usages', 'bi-box-arrow-in-right', TRUE, TRUE, 'Quản trị viên vừa check-in thiết bị Máy tính DELL Optiplex 001 (FPT-PC-001) tới không đổi phòng.', 'usage-checkin-10009-1', 'Check-in mới', 'primary', '2026-04-02 14:09:43.4848210', 1),
    (10039, 1, '2026-04-02 14:09:27.9394400', '/usages', 'bi-box-arrow-left', TRUE, TRUE, 'Quản trị viên vừa check-out thiết bị Máy tính DELL Optiplex 001 (FPT-PC-001).', 'usage-checkout-10009-1', 'Check-out mới', 'success', '2026-04-02 14:09:41.4350070', 1);

INSERT INTO public."chat_messages" ("id", "created_at", "is_system", "message", "message_type", "sender_id", "ticket_id")
VALUES
    (1, '2026-04-01 17:29:07.6327410', FALSE, '12', 'TEXT', 1, 2),
    (2, '2026-04-01 17:30:40.7089120', FALSE, '12', 'TEXT', 1, 2),
    (3, '2026-04-01 17:40:48.4080150', FALSE, '12', 'TEXT', 1, 2),
    (4, '2026-04-01 17:40:49.9571120', FALSE, '12', 'TEXT', 1, 2),
    (5, '2026-04-01 17:41:22.8546710', FALSE, '12', 'TEXT', 1, 2),
    (6, '2026-04-01 19:01:44.1002400', TRUE, 'Qu?n tr? viên dã t?o ticket TKT-1775044904026.', 'SYSTEM', 1, 3),
    (7, '2026-04-01 19:08:08.9756100', FALSE, 'Quốc', 'TEXT', 1, 3),
    (8, '2026-04-01 19:08:46.3753500', FALSE, 'Em đang kiểm rta', 'TEXT', 10005, 3),
    (9, '2026-04-01 19:08:58.9748880', FALSE, 'Ok', 'TEXT', 1, 3),
    (10, '2026-04-01 19:11:53.3256830', FALSE, 'Sản phẩm đang được sửa', 'TEXT', 10005, 3),
    (11, '2026-04-01 19:12:18.9232020', FALSE, '123', 'TEXT', 10005, 3),
    (12, '2026-04-01 19:12:41.7805780', FALSE, '123', 'TEXT', 10005, 3),
    (13, '2026-04-01 19:12:45.8161770', FALSE, '111', 'TEXT', 10005, 3),
    (14, '2026-04-01 19:17:37.7272680', FALSE, '12', 'TEXT', 10005, 3),
    (15, '2026-04-01 19:17:47.9109750', TRUE, 'Ticket được giao cho Phú Quốc Lê Phan.', 'SYSTEM', 1, 3),
    (16, '2026-04-01 19:17:54.7673060', TRUE, 'Ticket được giao cho Phú Quốc Lê Phan.', 'SYSTEM', 1, 3),
    (17, '2026-04-01 19:25:36.4630040', TRUE, 'Quản trị viên đã tạo ticket TKT-1775046336420.', 'SYSTEM', 1, 4),
    (18, '2026-04-01 19:35:40.9265150', TRUE, 'Quản trị viên đã cập nhật trạng thái sang Đang xử lý.', 'SYSTEM', 1, 4),
    (19, '2026-04-01 19:35:44.3239870', TRUE, 'Quản trị viên đã đánh dấu ticket là đã giải quyết.', 'SYSTEM', 1, 4),
    (20, '2026-04-01 19:35:50.9719170', TRUE, 'Ticket được giao cho Phú Quốc Lê Phan.', 'SYSTEM', 1, 3),
    (21, '2026-04-01 19:36:02.6570460', TRUE, 'Quản trị viên đã cập nhật trạng thái sang Đã giải quyết.', 'SYSTEM', 1, 3),
    (22, '2026-04-01 19:36:03.5914770', TRUE, 'Quản trị viên đã đánh dấu ticket là đã giải quyết.', 'SYSTEM', 1, 3),
    (23, '2026-04-01 19:36:19.5821720', TRUE, 'Quản trị viên đã tạo ticket TKT-1775046979544.', 'SYSTEM', 1, 5),
    (24, '2026-04-01 19:36:30.2860760', TRUE, 'Ticket được giao cho Phú Quốc Lê Phan.', 'SYSTEM', 1, 5),
    (25, '2026-04-01 20:36:01.6490730', TRUE, 'Quản trị viên đã cập nhật trạng thái sang Đã hủy.', 'SYSTEM', 1, 5),
    (26, '2026-04-01 22:45:33.5689850', TRUE, 'Quản trị viên đã tạoticket TKT-1775058333506.', 'SYSTEM', 1, 6),
    (10007, '2026-04-02 14:05:21.8596340', TRUE, 'Quản trị viên đã cập nhật trạng thái sang Đã hủy.', 'SYSTEM', 1, 6);

INSERT INTO public."audit_logs" ("id", "action_type", "created_at", "summary", "target_id", "target_type", "actor_user_id")
VALUES
    (1, 'USER_ROLE_CHANGED', '2026-03-31 17:44:49.3920250', 'Qu?n tr? viên da doi quyen cua Phú Qu?c Lê Phan tu STAFF sang MAINTENANCE.', 10005, 'USER', 1),
    (2, 'MAINTENANCE_ASSIGNED', '2026-03-31 17:44:58.4661850', 'Qu?n tr? viên da phan cong bao tri cho Phú Qu?c Lê Phan.', 1, 'ASSET', 1),
    (3, 'MAINTENANCE_RESOLVED', '2026-03-31 17:45:35.8605340', 'Qu?n tr? viên da xac nhan sua xong cho Máy tính DELL Optiplex 001.', 1, 'ASSET', 1),
    (4, 'ASSET_CHECKIN', '2026-03-31 17:52:31.3096570', 'Qu?n tr? viên dã check-in Máy tính DELL Optiplex 001 t?i Phòng h?c 102.', 1, 'ASSET', 1),
    (5, 'ASSET_CHECKOUT', '2026-03-31 17:52:34.9577770', 'Qu?n tr? viên dã check-out Máy tính DELL Optiplex 001 v? kho.', 1, 'ASSET', 1),
    (6, 'ASSET_CHECKIN', '2026-03-31 17:57:48.6911010', 'Quản trị viên đã check-in Máy tính DELL Optiplex 001 tới giữ nguyên vị trí.', 1, 'ASSET', 1),
    (7, 'ASSET_MARKED_LOST', '2026-03-31 21:33:05.9397090', 'Quản trị viên đã đánh dấu thất lạc thiết bị Máy tính DELL Optiplex 001. Vị trí ghi nhận cuối: Store Room.', 1, 'ASSET', 1),
    (8, 'ASSET_MARKED_FOUND', '2026-03-31 21:33:13.4013030', 'Quản trị viên đã đánh dấu tìm thấy thiết bị Máy tính DELL Optiplex 001 và chuyển về Store Room.', 1, 'ASSET', 1);

SELECT setval(
    pg_get_serial_sequence('public.roles', 'id'),
    (SELECT MAX(id) FROM public."roles")
);
SELECT setval(
    pg_get_serial_sequence('public.users', 'id'),
    (SELECT MAX(id) FROM public."users")
);
SELECT setval(
    pg_get_serial_sequence('public.rooms', 'id'),
    (SELECT MAX(id) FROM public."rooms")
);
SELECT setval(
    pg_get_serial_sequence('public.asset_categories', 'id'),
    (SELECT MAX(id) FROM public."asset_categories")
);
SELECT setval(
    pg_get_serial_sequence('public.assets', 'id'),
    (SELECT MAX(id) FROM public."assets")
);
SELECT setval(
    pg_get_serial_sequence('public.maintenance_requests', 'id'),
    (SELECT MAX(id) FROM public."maintenance_requests")
);
SELECT setval(
    pg_get_serial_sequence('public.asset_usages', 'id'),
    (SELECT MAX(id) FROM public."asset_usages")
);
SELECT setval(
    pg_get_serial_sequence('public.notifications', 'id'),
    (SELECT MAX(id) FROM public."notifications")
);
SELECT setval(
    pg_get_serial_sequence('public.chat_messages', 'id'),
    (SELECT MAX(id) FROM public."chat_messages")
);
SELECT setval(
    pg_get_serial_sequence('public.audit_logs', 'id'),
    (SELECT MAX(id) FROM public."audit_logs")
);
COMMIT;

