param(
    [string]$SqlServerContainer = "worshop-db-1",
    [string]$SqlDatabase = "FPTAssetDB",
    [string]$SqlUsername = "sa",
    [string]$SqlPassword = "tnimwiln1@",
    [string]$PostgresContainer = "postgre",
    [string]$PostgresDatabase = "fpt_asset_management",
    [string]$PostgresUsername = "postgres",
    [string]$OutputSqlPath = ".\mssql_to_postgres_migration.sql"
)

$ErrorActionPreference = "Stop"

$tables = @(
    "roles",
    "users",
    "rooms",
    "asset_categories",
    "assets",
    "maintenance_requests",
    "asset_usages",
    "notifications",
    "chat_messages",
    "audit_logs",
    "technician_coverage_rules",
    "ticket_attachments"
)

function Invoke-SqlServerQuery {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Query,
        [switch]$JsonMode
    )

    $arguments = @(
        "exec",
        $SqlServerContainer,
        "/opt/mssql-tools18/bin/sqlcmd",
        "-C",
        "-S", "localhost",
        "-U", $SqlUsername,
        "-P", $SqlPassword,
        "-d", $SqlDatabase,
        "-Q", $Query
    )

    if ($JsonMode) {
        $arguments += @("-y", "0", "-Y", "0", "-w", "65535")
    }
    else {
        $arguments += @("-h", "-1", "-W", "-w", "65535")
    }

    $lines = & docker @arguments

    if ($LASTEXITCODE -ne 0) {
        throw "SQL Server query failed."
    }

    return $lines
}

function Get-SqlServerColumns {
    param(
        [Parameter(Mandatory = $true)]
        [string]$TableName
    )

    $query = @"
SET NOCOUNT ON;
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = '$TableName'
ORDER BY ORDINAL_POSITION;
"@

    $lines = Invoke-SqlServerQuery -Query $query
    return @($lines | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" })
}

function Get-SqlServerRows {
    param(
        [Parameter(Mandatory = $true)]
        [string]$TableName
    )

    $query = @"
SET NOCOUNT ON;
SELECT *
FROM [$TableName]
FOR JSON PATH, INCLUDE_NULL_VALUES;
"@

    $lines = Invoke-SqlServerQuery -Query $query -JsonMode
    $jsonText = (
        $lines |
        ForEach-Object { $_.Trim() } |
        Where-Object {
            $_ -ne "" -and
            $_ -ne "JSON_F52E2B61-18A1-11d1-B105-00805F49916B" -and
            $_ -ne "----------------------------------------"
        }
    ) -join ""

    if ([string]::IsNullOrWhiteSpace($jsonText) -or $jsonText -eq "[]") {
        return @()
    }

    $rows = $jsonText | ConvertFrom-Json
    if ($rows -is [System.Array]) {
        return $rows
    }

    return @($rows)
}

function Get-PostgresColumns {
    param(
        [Parameter(Mandatory = $true)]
        [string]$TableName
    )

    $query = @"
SELECT column_name
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = '$TableName'
ORDER BY ordinal_position;
"@

    $lines = & docker exec $PostgresContainer psql `
        -U $PostgresUsername `
        -d $PostgresDatabase `
        -At `
        -c $query

    if ($LASTEXITCODE -ne 0) {
        throw "PostgreSQL column query failed for table '$TableName'."
    }

    return @($lines | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" })
}

function ConvertTo-PgLiteral {
    param(
        [AllowNull()]
        $Value
    )

    if ($null -eq $Value) {
        return "NULL"
    }

    if ($Value -is [bool]) {
        if ($Value) {
            return "TRUE"
        }

        return "FALSE"
    }

    if ($Value -is [datetime]) {
        return "'" + $Value.ToString("yyyy-MM-dd HH:mm:ss.fffffff", [System.Globalization.CultureInfo]::InvariantCulture) + "'"
    }

    if ($Value -is [byte[]]) {
        $hex = [System.BitConverter]::ToString($Value).Replace("-", "").ToLowerInvariant()
        return "decode('" + $hex + "', 'hex')"
    }

    if (
        $Value -is [byte] -or
        $Value -is [sbyte] -or
        $Value -is [int16] -or
        $Value -is [uint16] -or
        $Value -is [int32] -or
        $Value -is [uint32] -or
        $Value -is [int64] -or
        $Value -is [uint64] -or
        $Value -is [single] -or
        $Value -is [double] -or
        $Value -is [decimal]
    ) {
        return [System.Convert]::ToString($Value, [System.Globalization.CultureInfo]::InvariantCulture)
    }

    $escaped = [string]$Value
    $escaped = $escaped.Replace("'", "''")
    return "'" + $escaped + "'"
}

function New-QualifiedColumnList {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Columns
    )

    return ($Columns | ForEach-Object { '"' + $_ + '"' }) -join ", "
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("-- Generated by scripts/migrate-mssql-to-postgres.ps1")
[void]$builder.AppendLine("BEGIN;")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("TRUNCATE TABLE " + (($tables | ForEach-Object { 'public."' + $_ + '"' }) -join ", ") + " RESTART IDENTITY CASCADE;")
[void]$builder.AppendLine("")

$sequenceTables = [System.Collections.Generic.List[string]]::new()
$sourceCounts = @{}

foreach ($table in $tables) {
    Write-Host "Exporting $table from SQL Server..."

    $sourceColumns = Get-SqlServerColumns -TableName $table
    $targetColumns = Get-PostgresColumns -TableName $table
    $commonColumns = @($targetColumns | Where-Object { $sourceColumns -contains $_ })
    $rows = @(Get-SqlServerRows -TableName $table)

    $sourceCounts[$table] = $rows.Count

    if ($commonColumns.Count -eq 0) {
        throw "No shared columns found for table '$table'."
    }

    if ($targetColumns -contains "id" -and $rows.Count -gt 0) {
        [void]$sequenceTables.Add($table)
    }

    if ($rows.Count -eq 0) {
        continue
    }

    $columnList = New-QualifiedColumnList -Columns $commonColumns
    [void]$builder.AppendLine("INSERT INTO public.""$table"" ($columnList)")
    [void]$builder.AppendLine("VALUES")

    for ($index = 0; $index -lt $rows.Count; $index++) {
        $row = $rows[$index]
        $values = foreach ($column in $commonColumns) {
            ConvertTo-PgLiteral -Value $row.$column
        }

        $suffix = if ($index -lt ($rows.Count - 1)) { "," } else { ";" }
        [void]$builder.AppendLine("    (" + ($values -join ", ") + ")" + $suffix)
    }

    [void]$builder.AppendLine("")
}

foreach ($table in $sequenceTables) {
    [void]$builder.AppendLine("SELECT setval(")
    [void]$builder.AppendLine("    pg_get_serial_sequence('public.$table', 'id'),")
    [void]$builder.AppendLine("    (SELECT MAX(id) FROM public.`"$table`")")
    [void]$builder.AppendLine(");")
}

[void]$builder.AppendLine("COMMIT;")

$resolvedOutputPath = Resolve-Path -LiteralPath (Split-Path -Parent $OutputSqlPath) -ErrorAction SilentlyContinue
if ($null -eq $resolvedOutputPath) {
    $parent = Split-Path -Parent $OutputSqlPath
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
}

$builder.ToString() | Set-Content -LiteralPath $OutputSqlPath -Encoding UTF8

Write-Host "Generated migration SQL at $OutputSqlPath"
Write-Host ""
Write-Host "Source row counts:"
foreach ($table in $tables) {
    Write-Host ("- {0}: {1}" -f $table, $sourceCounts[$table])
}
